export const screens = [
    { region: "大台北和宜蘭地區", name: "國立海洋科技博物館", type: "8K投影機", sound: "", width: 29, height: 22, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北美麗華大直", type: "IMAX(雷射)", sound: "IMAX 12.1", width: 28.4, height: 21.2, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北國賓大戲院", type: "鉅院廳(雷射)", sound: "Dolby Atmos", width: 22, height: 12, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北松仁威秀", type: "TITAN(雷射)", sound: "Dolby 7.1", width: 22, height: 12, isOld: false },
    { region: "大台北和宜蘭地區", name: "新北新店裕隆城威秀", type: "IMAX(雷射)", sound: "", width: 21.4, height: 11.6, isOld: false },
    { region: "大台北和宜蘭地區", name: "新北板橋大遠百威秀", type: "IMAX(雷射)", sound: "", width: 21.3, height: 11.5, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北樂聲", type: "巨幕廳(雷射)", sound: "Dolby 7.1", width: 20, height: 10, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北西門in89", type: "LUXE", sound: "Dolby 7.1", width: 19.3, height: 8.3, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北美麗華大直", type: "Dolby Cinema", sound: "Dolby Atmos", width: 14.8, height: 7, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北西門in89", type: "COACH廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "新北板橋秀泰", type: "1廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "新北林口國賓", type: "2廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "宜蘭新月豪華", type: "1廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "新北林口國賓", type: "7廳", sound: "Barco Auro 11.1", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北美麗華大直", type: "1廳", sound: "Barco Auro 11.1", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "新北樹林秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "台北欣欣秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "大台北和宜蘭地區", name: "國立海洋科技博物館(已改裝)", type: "IMAX(已改裝)", sound: "", width: 28.4, height: 22, isOld: true },
    { region: "大台北和宜蘭地區", name: "美麗新淡海(暫停營業)", type: "1廳(雷射)", sound: "Dolby Atmos", width: 25, height: 13.5, isOld: true },
    { region: "大台北和宜蘭地區", name: "台北日新威秀(已歇業)", type: "IMAX", sound: "", width: 21.1, height: 11.3, isOld: true },
    { region: "大台北和宜蘭地區", name: "新北樹林秀泰(已改裝)", type: "巨幕廳(雷射)", sound: "Dolby 7.1", width: 0, height: 0, isOld: true },
    { region: "桃竹苗地區", name: "桃園新光影城", type: "Dolby Cinema*", sound: "Dolby Atmos", width: 20.00, height: 10.00, isOld: false },
    { region: "桃竹苗地區", name: "桃園美麗新台茂", type: "IMAX", sound: "", width: 17.80, height: 9.80, isOld: false },
    { region: "桃竹苗地區", name: "新竹巨城威秀", type: "IMAX", sound: "", width: 17.80, height: 9.70, isOld: false },
    { region: "桃竹苗地區", name: "桃園新光影城", type: "LUXE", sound: "Dolby Atmos", width: 17.00, height: 7.00, isOld: false },
    { region: "桃竹苗地區", name: "中壢威尼斯", type: "7、8廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "桃竹苗地區", name: "桃園八德國賓", type: "2、3廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "桃竹苗地區", name: "竹北百老匯影城", type: "8廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中大遠百威秀", type: "IMAX", sound: "", width: 18.30, height: 9.40, isOld: false },
    { region: "台中彰化地區", name: "台中老虎城威秀", type: "Titan", sound: "", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中文心秀泰", type: "11廳*", sound: "Dolby Atmos", width: 14.00, height: 7.00, isOld: false },
    { region: "台中彰化地區", name: "台中新光", type: "LUXE(雷射)", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中新光", type: "3(MX4D)、5廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中日日新", type: "6A星光廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中新時代大魯閣威秀", type: "1廳(雷射)*", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中日日新", type: "至尊廳(雷射)*", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中文心秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中站前秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "彰化員林影城", type: "A廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "台中彰化地區", name: "台中新光", type: "1廳(已改裝)", sound: "Dolby Atmos", width: 15.50, height: 6.60, isOld: true },
    { region: "台中彰化地區", name: "台中老虎城威秀", type: "IMAX(已改裝)", sound: "", width: 15.40, height: 8.60, isOld: true },
    { region: "台中彰化地區", name: "台中華威(已易主)", type: "1廳", sound: "Dolby Atmos", width: 14.30, height: 6.25, isOld: true },
    { region: "台中彰化地區", name: "台中凱擘影城(已易主)", type: "旗艦廳(雷射)", sound: "Dolby Atmos", width: 0, height: 0, isOld: true },
    { region: "嘉南高雄地區", name: "台南南紡威秀", type: "IMAX", sound: "", width: 21.80, height: 12.20, isOld: false },
    { region: "嘉南高雄地區", name: "嘉義in89豪華影城", type: "IMAX(雷射)", sound: "IMAX 12.1", width: 21.50, height: 12.30, isOld: false },
    { region: "嘉南高雄地區", name: "嘉義in89豪華影城", type: "LUXE", sound: "Dolby Atmos", width: 20.50, height: 10.50, isOld: false },
    { region: "嘉南高雄地區", name: "高雄夢時代秀泰", type: "巨幕廳(雷射)", sound: "Dolby 7.1", width: 19.00, height: 8.14, isOld: false },
    { region: "嘉南高雄地區", name: "高雄義大國賓", type: "8廳", sound: "Dolby 7.1", width: 20.00, height: 8.00, isOld: false },
    { region: "嘉南高雄地區", name: "高雄大遠百威秀", type: "IMAX(雷射)*", sound: "", width: 15.90, height: 8.20, isOld: false },
    { region: "嘉南高雄地區", name: "台南國賓", type: "A廳", sound: "Dolby 7.1", width: 15.50, height: 6.60, isOld: false },
    { region: "嘉南高雄地區", name: "高雄大魯閣草衙道國賓", type: "9、10廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "高雄MLD台鋁影城", type: "1廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "台南新光", type: "LUXE(雷射)", sound: "Dolby Atmos", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "嘉義in89", type: "MX4D、BB、Coach*", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "高雄夢時代秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "高雄岡山秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "嘉義秀泰", type: "ScreenX", sound: "Dolby 7.1", width: 0, height: 0, isOld: false },
    { region: "嘉南高雄地區", name: "岡山秀泰(已改裝)", type: "巨幕廳(已改裝)", sound: "Dolby 7.1", width: 20.00, height: 11.00, isOld: true },
    { region: "嘉南高雄地區", name: "夢時代喜滿客(已易主)", type: "CINE-X(雷射)*", sound: "", width: 20.00, height: 8.20, isOld: true },
    { region: "嘉南高雄地區", name: "台鋁秀泰影城(已易主)", type: "1廳", sound: "Dolby Atmos", width: 0, height: 0, isOld: true },
    { region: "嘉南高雄地區", name: "高雄奧斯卡影城(已歇業)", type: "1、8廳", sound: "DTS：X", width: 0, height: 0, isOld: true },
    { region: "嘉南高雄地區", name: "嘉義秀泰(已改裝)", type: "ScreenX(雷射)*", sound: "Dolby 7.1", width: 0, height: 0, isOld: true },
    { region: "東部和外島地區", name: "花蓮新天堂樂園威秀", type: "IMAX(雷射)*", sound: "IMAX 12.1", width: 21.30, height: 12.00, isOld: false },
    { region: "東部和外島地區", name: "金門金獅", type: "4D+ 影廳(A廳)*", sound: "Dolby Atmos", width: 22.20, height: 12.00, isOld: false }
];
